image_width: 1280
image_height: 720
camera_name: 135122071615
camera_matrix:
  rows: 3
  cols: 3
  data:
    [
      910.6444091796875,
      0.0,
      644.0233764648438,
      0.0,
      908.9205322265625,
      368.9620056152344,
      0.0,
      0.0,
      1.0,
    ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data:
    [
      910.6444091796875,
      0.0,
      644.0233764648438,
      0.0,
      0.0,
      908.9205322265625,
      368.9620056152344,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
    ]
